### PR TITLE
Save old config after update or remove

### LINKED ISSUE #1: rpm -U resulted in complete rewrite /etc/default/victoriametrics
rpm -U ... resulted in complete rewrite /etc/default/victoriametrics.

### PR DESCRIPTION
**Pull request by Karsonito**
Fixes #1

### CODE REVIEW

**Comment by patsevanton** [comment]
Sorry. I change version and later see you Pull request.
Can you chnage Pull request?

**Comment by Karsonito** [comment]
done )

**Comment by patsevanton** [comment]
Merged. Please try and will write here.

**Comment by Karsonito** [comment]
I've checked new package. It's seem _almost_ ok.
If package is removed old config keeps as victoriametrics.conf.rpmsave
If package is updated old config keeps as victoriametrics.conf, but new config from packege is not saved as victoriametrics.conf.rpmnew
May I am wrong, but I thought this is default behavior for rpm packages

**Comment by patsevanton** [comment]
Hm.. i don`t know how save new config to victoriametrics.conf.rpmnew

**Pull request merged**
